import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";
import fs from "fs/promises";
import path from "path";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

// Note: main.css removed - CSS is now bundled from src/styles/index.css to styles.css
const outputFiles = ["main.js", "styles.css", "manifest.json"];

async function copyOutputsToDist() {
	const distDir = path.resolve("dist");
	await fs.mkdir(distDir, { recursive: true });

	for (const file of outputFiles) {
		const target = path.join(distDir, file);
		await fs.rm(target, { force: true });
	}

	for (const file of outputFiles) {
		const source = path.resolve(file);
		const target = path.join(distDir, file);
		await fs.copyFile(source, target);
	}
}

// Shared esbuild options for externals
const externalModules = [
	"obsidian",
	"electron",
	"@codemirror/autocomplete",
	"@codemirror/collab",
	"@codemirror/commands",
	"@codemirror/language",
	"@codemirror/lint",
	"@codemirror/search",
	"@codemirror/state",
	"@codemirror/view",
	...builtinModules,
];

// JavaScript build context
const jsContext = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: externalModules,
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
	define: {
		DEBUG: prod ? "false" : "true",
	},
});

// CSS build context - bundles all CSS into styles.css for Obsidian
const cssContext = await esbuild.context({
	entryPoints: ["src/styles/index.css"],
	bundle: true,
	outfile: "styles.css",
	minify: prod,
	logLevel: "info",
});

if (prod) {
	await Promise.all([jsContext.rebuild(), cssContext.rebuild()]);
	await copyOutputsToDist();
	process.exit(0);
} else {
	await Promise.all([jsContext.watch(), cssContext.watch()]);
}
